
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:5000"   # Host:Container
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  frontend-lint:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    profiles: ["lint"]
    command: ["npm", "run", "lint"]
